# Generated by Django 5.2 on 2025-04-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0004_onetimepassword"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OneTimePassword",
        ),
    ]
